tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      cd /workspace
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      sudo dpkg -i session-manager-plugin.deb
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
      session-manager-plugin

  - name: postgres
    before: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev
    command: |
      export GITPOD_IP=$(curl ifconfig.me)
      bash "$THEIA_WORKSPACE_ROOT/bin/rds/update-sg-rule"

  - name: react-js
    before: |
      cd frontend-react-js
      npm install

  - name: oh-my-posh
    before: |
      sudo wget https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/posh-linux-amd64 -O /usr/local/bin/oh-my-posh
      sudo chmod +x /usr/local/bin/oh-my-posh

      mkdir ~/.poshthemes
      wget https://github.com/JanDeDobbeleer/oh-my-posh/releases/latest/download/themes.zip -O ~/.poshthemes/themes.zip
      unzip ~/.poshthemes/themes.zip -d ~/.poshthemes
      chmod u+rw ~/.poshthemes/*.omp.*
      rm ~/.poshthemes/themes.zip
    command: |
      echo "eval \"\$(oh-my-posh init bash --config ~/.poshthemes/stelbent-compact.minimal.omp.json)\"" >> ~/.bashrc
      source ~/.bashrc

  - name: python-pip
    command: |
      pip install -r backend-flask/requirements.txt

  - name: env-vars
    command: |
      ruby "$THEIA_WORKSPACE_ROOT/bin/frontend/generate-env"
      ruby "$THEIA_WORKSPACE_ROOT/bin/backend/generate-env"

  - name: cdk
    before: |
      cd "$THEIA_WORKSPACE_ROOT/aws/lambdas/process-images"
      npm install
      npm install aws-cdk -g
      cd "$THEIA_WORKSPACE_ROOT/thumbing-serverless-cdk"
      cp .env.example .env
      npm install
      bash "$THIEA_WORKSPACE_ROOT/bin/avatar/build"

vscode:
  extensions:
    - 42Crunch.vscode-openapi

ports:
  - name: frontend
    port: 3000
    onOpen: open-browser
    visibility: public
  - name: backend
    port: 4567
    visibility: public
  - name: xray-daemon
    port: 2000
    visibility: public
  - name: cognito-verifier
    port: 5555
    visibility: public