name: "Sync static website"
run-name: "Deploy Site Run: ${{ github.run_id }}"
on:
  workflow_dispatch:
  push:
    branches:
      - prod

jobs:
  build-and-sync-site:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build site
        env:
          REACT_APP_API_GATEWAY_ENDPOINT_URL: ${{ secrets.REACT_APP_API_GATEWAY_ENDPOINT_URL }}
          REACT_APP_AWS_USER_POOLS_ID: ${{ secrets.REACT_APP_AWS_USER_POOLS_ID }}
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          REACT_APP_AWS_COGNITO_REGION: ${{ vars.REACT_APP_AWS_COGNITO_REGION }}
          REACT_APP_AWS_PROJECT_REGION: ${{ vars.REACT_APP_AWS_PROJECT_REGION }}
          REACT_APP_BACKEND_URL: ${{ vars.REACT_APP_BACKEND_URL }}
          CI: false # in order not to treat warning as errors. CI = true will treat warning as erros which is the default.
        run: |
          cd frontend-react-js
          npm ci
          npm run build

      - name: Init Ruby environment
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "3.1"

      - name: Sync static site
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          GITHUB_ACTIONS_WORKFLOW: true
        run: |
          echo "===========Installing gems==========="
          bundle install
          bundle update --bundler
          echo "==============Syncing================"
          bin/frontend/sync
